<script setup lang="ts">
import { computed, ref } from 'vue'
import { Activity, Check, CheckCircle2, ChevronRight, CircleHelp, Layers3, Play, RotateCcw, Send, Server, Square, Zap } from 'lucide-vue-next'
import type { LabEvent, Snapshot } from './types'

const props = defineProps<{ snapshot: Snapshot; mode: 'demo' | 'live'; busy: boolean; editable: boolean; payload: string; checks: boolean[] }>()
const emit = defineEmits<{ action: [kind: 'publish' | 'start' | 'stop' | 'ack' | 'process' | 'crash']; 'update:payload': [value: string]; event: [event: LabEvent]; reset: []; check: [index: number]; notes: []; guide: [] }>()
const scenario = ref<'before' | 'after'>('before')
const labels: Record<string,string> = { PUBLISH_SENT: '발행 요청 전송', DELIVERED: 'Consumer 전달', PROCESSED: '업무 반영', ACK_SENT: 'ACK 전송', WORKER_KILLED: '강제 종료', WORKER_EXITED: '프로세스 종료', CONSUMER_STARTED: 'Consumer 시작', CONNECTION_CLOSED: '연결 종료' }
const short = (id: string) => id ? id.slice(0, 8) : '—'
const time = (timestamp: string) => new Date(timestamp).toLocaleTimeString('ko-KR', { hour12: false })
const currentMessage = computed(() => props.snapshot.pending?.message_id || props.snapshot.events.find(e => e.event_type === 'DELIVERED')?.message_id || '')
const effects = computed(() => props.snapshot.effect_counts?.[currentMessage.value] || 0)
const attempts = computed(() => props.snapshot.events.filter(e => e.message_id === currentMessage.value && e.event_type === 'DELIVERED').reverse().map(e => ({ ...e, processed: props.snapshot.events.some(x => x.attempt_id === e.attempt_id && x.event_type === 'PROCESSED'), acked: props.snapshot.events.some(x => x.attempt_id === e.attempt_id && x.event_type === 'ACK_SENT'), killed: props.snapshot.events.some(x => x.attempt_id === e.attempt_id && x.event_type === 'WORKER_KILLED') })))
const instructions = computed(() => scenario.value === 'before' ? ['메시지 1개를 발행하고 Consumer를 시작합니다.', '업무를 반영한 뒤 ACK를 보내지 않고 강제 종료합니다.', 'Consumer를 다시 시작하고 같은 Message ID와 새 Attempt ID를 확인합니다.', '재전달된 메시지의 업무를 다시 반영한 뒤 ACK를 보냅니다.'] : ['새 메시지 1개를 발행하고 Consumer를 시작합니다.', '업무를 반영한 뒤 ACK를 보냅니다.', 'Ready·Unacked가 0으로 수집된 것을 확인하고 강제 종료합니다.', 'Consumer를 다시 시작하고 메시지가 재전달되지 않는지 확인합니다.'])
const criteria = ['ACK 전 종료 후 같은 메시지가 재전달되는 것을 확인했다.', '업무 반영과 ACK가 별개이며 중복 업무가 생길 수 있음을 설명한다.', 'Broker가 ACK를 반영한 뒤 종료한 경우와 결과를 비교했다.']
</script>

<template>
  <div class="phase-two">
    <div class="question-banner"><span class="question-icon"><CircleHelp :size="22" /></span><div><span>이번 실험의 질문</span><strong>처리는 끝났는데 ACK 전에 죽으면, 업무가 다시 실행될까?</strong></div><button class="text-button" @click="emit('guide')">개념 살펴보기 <ChevronRight :size="15" /></button></div>
    <div class="scenario-grid"><button class="scenario-card" :class="{ chosen: scenario === 'before' }" @click="scenario = 'before'"><span class="scenario-number">실험 A</span><strong>ACK 전 강제 종료</strong><span>업무 반영 → 종료 → 재전달 → 중복 업무</span><span class="scenario-result">예상: 같은 Message ID, 새로운 처리 시도</span></button><button class="scenario-card" :class="{ chosen: scenario === 'after' }" @click="scenario = 'after'"><span class="scenario-number">실험 B</span><strong>ACK 후 강제 종료</strong><span>업무 반영 → ACK 반영 확인 → 종료</span><span class="scenario-result">예상: 확인된 메시지는 다시 전달되지 않음</span></button></div>
    <div class="metric-grid"><div class="metric-card"><div class="metric-label"><Layers3 :size="16" /> Ready</div><div class="metric-value blue">{{ snapshot.queue.ready }}</div><div class="metric-foot">Queue {{ snapshot.queue.name }}</div></div><div class="metric-card"><div class="metric-label"><Activity :size="16" /> Unacked</div><div class="metric-value amber">{{ snapshot.queue.unacked }}</div><div class="metric-foot">전달됐지만 ACK가 없는 메시지</div></div><div class="metric-card"><div class="metric-label"><RotateCcw :size="16" /> 전달 시도</div><div class="metric-value">{{ attempts.length }}<span>attempts</span></div><div class="metric-foot">현재 메시지 · 관측 이력 기준</div></div><div class="metric-card"><div class="metric-label"><CheckCircle2 :size="16" /> 업무 반영</div><div class="metric-value" :class="{ amber: effects > 1 }">{{ effects }}<span>effects</span></div><div class="metric-foot">현재 메시지 · 학습용 기록 횟수</div></div></div>
    <div class="work-grid"><section class="panel producer-panel"><div class="panel-heading"><h2><Send :size="17" /> 실험 준비</h2><span class="small-badge">ONE MESSAGE</span></div><label for="phase2-message">Message payload</label><div class="editor"><div class="editor-top"><span>TEXT</span><span>UTF-8</span></div><textarea id="phase2-message" :value="payload" rows="2" maxlength="4096" spellcheck="false" @input="emit('update:payload', ($event.target as HTMLTextAreaElement).value)"></textarea></div><div class="button-row"><button class="button primary" :disabled="busy || !editable || !!snapshot.pending || snapshot.queue.ready > 0 || snapshot.consumer_active" @click="emit('action', 'publish')"><Send :size="15" /> 메시지 1개 발행</button><button class="button secondary" :disabled="busy || !editable || snapshot.consumer_active" @click="emit('action', 'start')"><Play :size="15" /> Consumer 시작</button></div><p class="hint">Phase 1과 분리된 실습 Queue를 사용합니다. 실험 전 기존 Consumer를 멈추고 대기 메시지를 확인하세요.</p><ol class="phase2-instructions"><li v-for="(instruction, index) in instructions" :key="instruction"><span>{{ index + 1 }}</span>{{ instruction }}</li></ol></section>
    <section class="panel consumer-panel"><div class="panel-heading"><h2><Server :size="17" /> 실습 Consumer 프로세스</h2><span class="small-badge" :class="{ 'active-badge': snapshot.consumer_active }">{{ snapshot.consumer_active ? 'RUNNING' : 'STOPPED' }}</span></div><div class="consumer-toolbar"><div><strong>consumer-phase2</strong><span>별도 프로세스 <span class="dot-divider">·</span> Manual ACK / Prefetch 1</span></div><button class="button secondary" :disabled="busy || !editable || !snapshot.consumer_active" @click="emit('action', 'stop')"><Square :size="13" /> 정상 종료</button></div><div v-if="snapshot.pending" class="delivery-box"><div class="delivery-title"><span>{{ snapshot.pending.processed ? '업무 반영됨 · ACK 대기' : '전달됨 · 업무 반영 대기' }}</span><span class="redelivery-badge" v-if="snapshot.pending.redelivered">REDELIVERED</span></div><pre>{{ snapshot.pending.body }}</pre><dl class="message-identifiers"><div><dt>Message ID</dt><dd>{{ short(snapshot.pending.message_id) }}</dd></div><div><dt>Attempt ID</dt><dd>{{ short(snapshot.pending.attempt_id) }}</dd></div></dl><div class="button-row"><button class="button secondary" :disabled="busy || !editable || snapshot.pending.processed" @click="emit('action', 'process')"><CheckCircle2 :size="15" /> 업무 반영</button><button class="button primary" :disabled="busy || !editable || !snapshot.pending.processed" @click="emit('action', 'ack')"><Check :size="15" /> ACK 보내기</button></div></div><div v-else class="consumer-empty"><div class="empty-icon"><Server :size="24" /></div><strong>{{ snapshot.consumer_active ? '전달을 기다리는 중입니다' : '실습 프로세스가 멈춰 있습니다' }}</strong><p>{{ snapshot.consumer_active ? 'ACK 후 실험은 Queue 수집값을 확인한 뒤 종료하세요.' : '새 실험은 발행, 재전달 실험은 Consumer 시작으로 이어갑니다.' }}</p></div><div class="crash-control"><button class="button danger" :disabled="busy || !editable || !snapshot.consumer_active" @click="emit('action', 'crash')"><Zap :size="15" /> Consumer 강제 종료</button><span>이 실습에서 만든 Consumer만 종료합니다.</span></div></section></div>
    <section class="panel attempt-panel"><div class="panel-heading"><h2><RotateCcw :size="17" /> 같은 메시지, 다른 처리 시도</h2><code class="subtle">Message {{ short(currentMessage) }}</code></div><div v-if="!attempts.length" class="events-empty"><Activity :size="20" /><div><strong>Consumer가 받은 메시지의 시도 이력이 여기에 나타납니다.</strong><p>재전달되어도 Message ID는 유지되고, Attempt ID는 새로 생깁니다.</p></div></div><div v-else class="attempt-list"><div v-for="(attempt, index) in attempts" :key="attempt.event_id" class="attempt-row"><span class="attempt-index">{{ index + 1 }}</span><div><strong>시도 {{ short(attempt.attempt_id || '') }}</strong><span>{{ time(attempt.timestamp) }} · {{ attempt.metadata.redelivered ? '재전달' : '첫 전달' }}</span></div><span class="attempt-state" :class="{ reflected: attempt.processed }">{{ attempt.processed ? '업무 반영됨' : '업무 미반영' }}</span><span class="attempt-state" :class="{ acked: attempt.acked, killed: attempt.killed && !attempt.acked }">{{ attempt.acked ? 'ACK 전송' : attempt.killed ? 'ACK 전 종료' : 'ACK 대기' }}</span></div></div><div v-if="effects > 1" class="duplicate-insight"><CircleHelp :size="18" /><span>한 메시지의 업무가 {{ effects }}번 반영됐습니다. 재전달은 정상 복구 동작이어도 업무 중복은 별도로 막아야 합니다. Phase 6에서 멱등성을 구현합니다.</span></div></section>
    <div class="bottom-grid"><section class="panel events-panel"><div class="panel-heading"><h2><Activity :size="17" /> Phase 2 관측 이벤트</h2><div class="heading-actions"><span class="subtle">{{ mode === 'demo' ? '예시 시뮬레이션' : '실제 프로세스 기록' }}</span><button v-if="mode === 'demo'" class="icon-button" aria-label="Phase 2 예시 초기화" @click="emit('reset')"><RotateCcw :size="15" /></button></div></div><div v-if="!snapshot.events.length" class="events-empty"><p>메시지를 보내고 두 종료 시점을 비교해 보세요.</p></div><div v-else class="event-table"><div class="event-table-head"><span>시각</span><span>이벤트</span><span>Message ID</span></div><button v-for="event in snapshot.events.slice(0, 15)" :key="event.event_id" class="event-row" :disabled="!event.message_id" @click="emit('event', event)"><code>{{ time(event.timestamp) }}</code><span class="event-name"><i></i>{{ labels[event.event_type] || event.event_type }}</span><code>{{ short(event.message_id) }}</code></button></div><div class="table-footer">업무 반영은 실제 모드에서 디스크에 저장한 학습용 기록입니다. 실제 결제나 외부 업무를 실행하지 않습니다.</div></section><section class="panel checklist-panel"><div class="panel-heading"><h2><CheckCircle2 :size="17" /> Phase 2 완료 기준</h2></div><button v-for="(criterion, index) in criteria" :key="criterion" class="check-row" @click="emit('check', index)"><span class="checkbox" :class="{ checked: checks[index] }"><Check v-if="checks[index]" :size="13" /></span><span>{{ criterion }}</span></button><div class="checklist-footer"><span>체크는 현재 기기에 저장됩니다.</span><button class="text-button" @click="emit('notes')">차이를 기록하기 <ChevronRight :size="14" /></button></div></section></div>
    <div class="mode-footnote"><CircleHelp :size="15" /><span>{{ mode === 'demo' ? '설명용 예시에서는 종료와 재전달을 즉시 재현합니다. 실제 모드에서는 Broker의 연결 종료 감지와 지표 수집에 시간이 걸릴 수 있습니다.' : 'ACK_SENT는 전송 기록입니다. ACK 후 실험은 Ready·Unacked가 0으로 관측된 뒤 종료하세요. API를 재시작해도 업무 반영 기록은 디스크에 남습니다.' }}</span></div>
  </div>
</template>
